### ISSUE TITLE
__init__() got an unexpected keyword argument 'gpus'

### ISSUE THREAD

**Issue by gwcde** [lcn-kul/madress-2023#1]
trainer_params = {
        "gpus": gpus,
        "max_epochs": TRAIN_ARGS.max_epochs,
        "callbacks": all_callbacks,
        "enable_progress_bar": True,
        "num_sanity_val_steps": 2,
        "log_every_n_steps": 10,
        "logger": tb_logger,
        "deterministic": True,
    }
when run the  trainer = pl.Trainer(**trainer_params), the error:__init__() got an unexpected keyword argument 'gpus' occur

**Comment by btamm12** [comment]
Thanks for bringing this up. It looks like it should be "devices" instead of "gpus" if you're using PyTorch Lightning >= 2.0.
I will specify the Pytorch Lightning version in the requirements, so this doesn't break. (3addf95)
